In [1]:
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

# Loading the Train data

In [3]:
train_df=pd.read_parquet(r'C:\Users\91882\Downloads\train.parquet',engine='pyarrow')

In [4]:
train_df

Patient-Uid       Date           Incident
0         a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2019-03-09  PRIMARY_DIAGNOSIS
1         a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f 2015-05-16  PRIMARY_DIAGNOSIS
3         a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f 2018-01-30     SYMPTOM_TYPE_0
4         a0dc950b-1c7c-11ec-b6ec-16262ee38c7f 2015-04-22        DRUG_TYPE_0
8         a0dc9543-1c7c-11ec-bb63-16262ee38c7f 2016-06-18        DRUG_TYPE_1
...                                        ...        ...                ...
29080886  a0ee9f75-1c7c-11ec-94c7-16262ee38c7f 2018-07-06        DRUG_TYPE_6
29080897  a0ee1284-1c7c-11ec-a3d5-16262ee38c7f 2017-12-29        DRUG_TYPE_6
29080900  a0ee9b26-1c7c-11ec-8a40-16262ee38c7f 2018-10-18       DRUG_TYPE_10
29080903  a0ee1a92-1c7c-11ec-8341-16262ee38c7f 2015-09-18        DRUG_TYPE_6
29080911  a0ee146e-1c7c-11ec-baee-16262ee38c7f 2018-10-05        DRUG_TYPE_1

[3220868 rows x 3 columns]

In [5]:
train_df.shape

(3220868, 3)

In [6]:
train_df.columns

Index(['Patient-Uid', 'Date', 'Incident'], dtype='object')

# Let's see how many patients are in train data

In [7]:
len(train_df['Patient-Uid'].unique())

27033

# Let's see How many types of drug are using in train data

In [8]:
len(train_df['Incident'].unique())

57



# Loading the test data

In [9]:
test_df=pd.read_parquet(r"C:\Users\91882\Downloads\test.parquet")

In [10]:
test_df

Patient-Uid       Date        Incident
0        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08  SYMPTOM_TYPE_0
1        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17     DRUG_TYPE_0
2        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01     DRUG_TYPE_2
3        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05     DRUG_TYPE_1
4        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-11-04  SYMPTOM_TYPE_0
...                                       ...        ...             ...
1372854  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-05-11    DRUG_TYPE_13
1372856  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2018-08-22     DRUG_TYPE_2
1372857  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-02-04     DRUG_TYPE_2
1372858  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-09-25     DRUG_TYPE_8
1372859  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-05-19     DRUG_TYPE_7

[1065524 rows x 3 columns]

# Let's see how many patients are in test data

In [11]:
len(test_df['Patient-Uid'].unique())

11482

# Let's see How many types of drug are using in test data

In [12]:
len(test_df['Incident'].unique())

55

# ------------------Train data-------------------------

In [13]:
train_df['Incident'] = train_df['Incident'].replace('TARGET DRUG', 'TARGET_DRUG')

### Grouping

In [14]:
train_df['Date'] = pd.to_datetime(train_df['Date'])

In [15]:
train_df.sort_values(by=['Patient-Uid', 'Date'], inplace=True)

In [16]:
train_df_group = train_df.groupby('Patient-Uid')['Incident'].apply(lambda x: ' '.join(x)).reset_index()

In [17]:
train_df_group['Incident'][0]

'DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM_TYPE_0 DRUG_TYPE_9 DRUG_TYPE_0 TEST_TYPE_0 DRUG_TYPE_11 DRUG_TYPE_7 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_7 TEST_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 TEST_TYPE_0 PRIMARY_DIAGNOSIS TEST_TYPE_1 TEST_TYPE_0 DRUG_TYPE_2 SYMPTOM_TYPE_0 DRUG_TYPE_0 PRIMARY_DIAGNOSIS TEST_TYPE_0 DRUG_TYPE_2 PRIMARY_DIAGNOSIS DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_8 DRUG_TYPE_0 DRUG_TYPE_0 PRIMARY_DIAGNOSIS SYMPTOM_TYPE_0 PRIMARY_DIAGNOSIS PRIMARY_DIAGNOSIS SYMPTOM_TYPE_2 DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_6 SYMPTOM_TYPE_7 PRIMARY_DIAGNOSIS DRUG_TYPE_0 DRUG_TYPE_8 DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_2 TEST_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_0 SYMPTOM_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DIAGNOSIS TEST_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_0 TEST_TYPE_0 PRIMARY_DIA

In [18]:
train_df_group

Patient-Uid  \
0      a0db1e73-1c7c-11ec-ae39-16262ee38c7f   
1      a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f   
2      a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f   
3      a0dc950b-1c7c-11ec-b6ec-16262ee38c7f   
4      a0dc9543-1c7c-11ec-bb63-16262ee38c7f   
...                                     ...   
27028  a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f   
27029  a0f0d4f4-1c7c-11ec-b144-16262ee38c7f   
27030  a0f0d523-1c7c-11ec-89d2-16262ee38c7f   
27031  a0f0d553-1c7c-11ec-a70a-16262ee38c7f   
27032  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f   

                                                Incident  
0      DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...  
1      DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...  
2      DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...  
3      DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...  
4      DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...  
...                                                  ...  
27028  DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_...  
27029  DRUG_TYPE_6 DRUG_TYPE_8 DRUG_TYPE_1 DRUG_TYPE_...  
27030  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_9 DRUG_TYPE_...  
27031  DRUG_TYPE_9 SYMPTOM_TYPE_7 DRUG_TYPE_2 DRUG_TY...  
27032  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_...  

[27033 rows x 2 columns]

### Positive-set and Negative-set¶

In [19]:
train_df_group['classes'] = train_df_group['Incident'].apply(lambda x: 1 if 'TARGET_DRUG' in x.split() else 0)

In [20]:
train_df_group

Patient-Uid  \
0      a0db1e73-1c7c-11ec-ae39-16262ee38c7f   
1      a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f   
2      a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f   
3      a0dc950b-1c7c-11ec-b6ec-16262ee38c7f   
4      a0dc9543-1c7c-11ec-bb63-16262ee38c7f   
...                                     ...   
27028  a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f   
27029  a0f0d4f4-1c7c-11ec-b144-16262ee38c7f   
27030  a0f0d523-1c7c-11ec-89d2-16262ee38c7f   
27031  a0f0d553-1c7c-11ec-a70a-16262ee38c7f   
27032  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f   

                                                Incident  classes  
0      DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...        0  
1      DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...        0  
2      DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...        0  
3      DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...        0  
4      DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...        0  
...                                                  ...      ...  
27028  DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_...        1  
27029  DRUG_TYPE_6 DRUG_TYPE_8 DRUG_TYPE_1 DRUG_TYPE_...        1  
27030  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_9 DRUG_TYPE_...        1  
27031  DRUG_TYPE_9 SYMPTOM_TYPE_7 DRUG_TYPE_2 DRUG_TY...        1  
27032  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_...        1  

[27033 rows x 3 columns]

# -------------Analysis for 30 days---------------------

In [21]:
patients= train_df.groupby("Patient-Uid")
patients.head()

Patient-Uid       Date        Incident
1750087   a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2015-09-22     DRUG_TYPE_7
1473893   a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2018-04-13  SYMPTOM_TYPE_2
1387922   a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2018-05-02     DRUG_TYPE_7
223191    a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2018-11-23  SYMPTOM_TYPE_0
557302    a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2018-11-23     DRUG_TYPE_9
...                                        ...        ...             ...
19365046  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f 2015-04-21     DRUG_TYPE_6
19365755  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f 2015-06-26     DRUG_TYPE_1
20630372  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f 2015-07-16     DRUG_TYPE_6
22527539  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f 2015-07-16     DRUG_TYPE_5
13222187  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f 2015-08-06     TEST_TYPE_1

[135165 rows x 3 columns]

Exclude patient records from the positive class occurring within 30 days prior to taking the "TARGET_DRUG," leaving negative class patients unaffected.

# Steps:

#### Step1:iterating through the dates of the patient records and checking if he has taken the “TARGET_DRUG”.

#### Step2:If they have taken it , note down the index of the date( or drug ) taken before 30 days of the date of the “TARGET_DRUG”.


#### Step3:Now all these position indexes are stored in the list called “cutoff_index_list”

#### Step4:During the analysis we have encountered a patient, who has takent the “TARGET_DRUG” before 30 days itself like with in 6 days of the joining the clinic or atleast when the records are started on their name.

#### Step5:Finally we also note down those patients-id also to remove them. As their data is of no use and are treated as outliers.

In [22]:
target_count=0 

cutoff_index_list=[]
index_of_target=[]

outlier_patients=0

outlier_patients_index=[]

for group_name, group_data in patients:
    for i in range(len(group_data)):

        if group_data["Incident"].iloc[i]=="TARGET_DRUG":
            index_of_target.append(i)  
            target_count+=1
            temp = i 
            while (group_data["Date"].iloc[i]-group_data["Date"].iloc[temp-1]).days < 30:
                temp-=1
                if temp==0:
                    outlier_patients+=1
                    outlier_patients_index.append(group_name)
                    break
            cutoff_index_list.append(temp)
            break
        if i == len(group_data)-1:
            cutoff_index_list.append(len(group_data))

In [23]:
print("Patient count who taken TARGET_DRUG :", target_count)

print("Patients who are administered TARGET_DRUG within 30 days of given records itself :", outlier_patients)


Patient count who taken TARGET_DRUG : 9374
Patients who are administered TARGET_DRUG within 30 days of given records itself : 1


#### Patients who are administered TARGET_DRUG within 30 days of given records itself

In [24]:
outlier_patients_index

['a0ee64e1-1c7c-11ec-becd-16262ee38c7f']

### Adding cut-off to the grouped train df

In [25]:
train_df_group['cutoff_indices']=cutoff_index_list
train_df_group.head()

Patient-Uid  \
0  a0db1e73-1c7c-11ec-ae39-16262ee38c7f   
1  a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f   
2  a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f   
3  a0dc950b-1c7c-11ec-b6ec-16262ee38c7f   
4  a0dc9543-1c7c-11ec-bb63-16262ee38c7f   

                                            Incident  classes  cutoff_indices  
0  DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...        0              96  
1  DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...        0             109  
2  DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...        0              98  
3  DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...        0             109  
4  DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...        0             244

In [26]:
train_df_group.shape

(27033, 4)

#### Removing that member

In [27]:
out=outlier_patients_index[0]
out

'a0ee64e1-1c7c-11ec-becd-16262ee38c7f'

In [28]:
train_df_group=train_df_group[train_df_group["Patient-Uid"]!=outlier_patients_index[0]]

In [29]:
train_df_group

Patient-Uid  \
0      a0db1e73-1c7c-11ec-ae39-16262ee38c7f   
1      a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f   
2      a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f   
3      a0dc950b-1c7c-11ec-b6ec-16262ee38c7f   
4      a0dc9543-1c7c-11ec-bb63-16262ee38c7f   
...                                     ...   
27028  a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f   
27029  a0f0d4f4-1c7c-11ec-b144-16262ee38c7f   
27030  a0f0d523-1c7c-11ec-89d2-16262ee38c7f   
27031  a0f0d553-1c7c-11ec-a70a-16262ee38c7f   
27032  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f   

                                                Incident  classes  \
0      DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...        0   
1      DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...        0   
2      DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...        0   
3      DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...        0   
4      DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...        0   
...                                                  ...      ...   
27028  DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_...        1   
27029  DRUG_TYPE_6 DRUG_TYPE_8 DRUG_TYPE_1 DRUG_TYPE_...        1   
27030  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_9 DRUG_TYPE_...        1   
27031  DRUG_TYPE_9 SYMPTOM_TYPE_7 DRUG_TYPE_2 DRUG_TY...        1   
27032  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_...        1   

       cutoff_indices  
0                  96  
1                 109  
2                  98  
3                 109  
4                 244  
...               ...  
27028              82  
27029              82  
27030             107  
27031             120  
27032              76  

[27032 rows x 4 columns]

##### finally removed the outlier patient

### Extracting Pre-Onset Patient History: Ensuring Model Predicts Disease Onset from Past Data

In [30]:
train_df_group=train_df_group.groupby('Patient-Uid')

In [31]:
def process_text(group):
    group['Incident_Drug'] = group.apply(lambda row: ' '.join(row['Incident'].split()[:row['cutoff_indices']]), axis=1)
    return group

train_updated_group = train_df_group.apply(process_text)

train_updated_group

Patient-Uid  \
0      a0db1e73-1c7c-11ec-ae39-16262ee38c7f   
1      a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f   
2      a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f   
3      a0dc950b-1c7c-11ec-b6ec-16262ee38c7f   
4      a0dc9543-1c7c-11ec-bb63-16262ee38c7f   
...                                     ...   
27028  a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f   
27029  a0f0d4f4-1c7c-11ec-b144-16262ee38c7f   
27030  a0f0d523-1c7c-11ec-89d2-16262ee38c7f   
27031  a0f0d553-1c7c-11ec-a70a-16262ee38c7f   
27032  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f   

                                                Incident  classes  \
0      DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...        0   
1      DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...        0   
2      DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...        0   
3      DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...        0   
4      DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...        0   
...                                                  ...      ...   
27028  DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_...        1   
27029  DRUG_TYPE_6 DRUG_TYPE_8 DRUG_TYPE_1 DRUG_TYPE_...        1   
27030  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_9 DRUG_TYPE_...        1   
27031  DRUG_TYPE_9 SYMPTOM_TYPE_7 DRUG_TYPE_2 DRUG_TY...        1   
27032  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_...        1   

       cutoff_indices                                      Incident_Drug  
0                  96  DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...  
1                 109  DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...  
2                  98  DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...  
3                 109  DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...  
4                 244  DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...  
...               ...                                                ...  
27028              82  DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_...  
27029              82  DRUG_TYPE_6 DRUG_TYPE_8 DRUG_TYPE_1 DRUG_TYPE_...  
27030             107  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_9 DRUG_TYPE_...  
27031             120  DRUG_TYPE_9 SYMPTOM_TYPE_7 DRUG_TYPE_2 DRUG_TY...  
27032              76  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_...  

[27032 rows x 5 columns]

# Feature Engineering

#### Time based feature engineering

In [32]:
train_df=train_df[train_df['Patient-Uid']!='a0ee64e1-1c7c-11ec-becd-16262ee38c7f']
grouped= train_df.groupby('Patient-Uid')
print(grouped.ngroups)

27032


In [33]:
# Define pds as an iterator over your patient data
# Example data structure:
# pds = [(patient_id_1, patient_data_1), (patient_id_2, patient_data_2), ...]

count = 0
Time = []

# Iterate through the records of each patient
for patient_id, patient_data in grouped:
    # List to store the gap history of each patient
    tem = []
    # Loop through the patient history
    for j in range(train_updated_group['cutoff_indices'].iloc[count] - 1):
        # Calculate the difference between consecutive dates in days
        gap = (patient_data["Date"].iloc[j + 1] - patient_data["Date"].iloc[j]).days
        tem.append(gap)
    
    # Pad the gap vector with zeros to match the max_length
    tem.extend([0] * (max(cutoff_index_list) - len(tem)))

    # Finally, add the patient's gap history to the list
    Time.append(tem)
    
    count += 1  # Increment the count for the next patient


In [34]:
print(len(Time),len(Time[0]))

27032 1645


In [35]:
#add them to the main dataset
train_updated_group['Time_based_features']=Time

In [36]:
train_updated_group

Patient-Uid  \
0      a0db1e73-1c7c-11ec-ae39-16262ee38c7f   
1      a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f   
2      a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f   
3      a0dc950b-1c7c-11ec-b6ec-16262ee38c7f   
4      a0dc9543-1c7c-11ec-bb63-16262ee38c7f   
...                                     ...   
27028  a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f   
27029  a0f0d4f4-1c7c-11ec-b144-16262ee38c7f   
27030  a0f0d523-1c7c-11ec-89d2-16262ee38c7f   
27031  a0f0d553-1c7c-11ec-a70a-16262ee38c7f   
27032  a0f0d582-1c7c-11ec-a6c1-16262ee38c7f   

                                                Incident  classes  \
0      DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...        0   
1      DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...        0   
2      DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...        0   
3      DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...        0   
4      DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...        0   
...                                                  ...      ...   
27028  DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_...        1   
27029  DRUG_TYPE_6 DRUG_TYPE_8 DRUG_TYPE_1 DRUG_TYPE_...        1   
27030  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_9 DRUG_TYPE_...        1   
27031  DRUG_TYPE_9 SYMPTOM_TYPE_7 DRUG_TYPE_2 DRUG_TY...        1   
27032  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_...        1   

       cutoff_indices                                      Incident_Drug  \
0                  96  DRUG_TYPE_7 SYMPTOM_TYPE_2 DRUG_TYPE_7 SYMPTOM...   
1                 109  DRUG_TYPE_0 DRUG_TYPE_2 DRUG_TYPE_0 PRIMARY_DI...   
2                  98  DRUG_TYPE_0 PRIMARY_DIAGNOSIS DRUG_TYPE_7 DRUG...   
3                 109  DRUG_TYPE_0 DRUG_TYPE_7 DRUG_TYPE_2 PRIMARY_DI...   
4                 244  DRUG_TYPE_1 TEST_TYPE_1 SYMPTOM_TYPE_8 DRUG_TY...   
...               ...                                                ...   
27028              82  DRUG_TYPE_6 DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_...   
27029              82  DRUG_TYPE_6 DRUG_TYPE_8 DRUG_TYPE_1 DRUG_TYPE_...   
27030             107  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_9 DRUG_TYPE_...   
27031             120  DRUG_TYPE_9 SYMPTOM_TYPE_7 DRUG_TYPE_2 DRUG_TY...   
27032              76  DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_...   

                                     Time_based_features  
0      [934, 19, 205, 0, 0, 0, 0, 1, 0, 8, 0, 53, 6, ...  
1      [2, 0, 32, 1, 0, 1, 0, 0, 0, 0, 59, 0, 0, 8, 3...  
2      [0, 0, 0, 0, 1, 13, 0, 0, 0, 0, 0, 0, 48, 51, ...  
3      [0, 62, 0, 17, 9, 0, 46, 48, 44, 20, 5, 0, 0, ...  
4      [10, 8, 10, 6, 17, 0, 3, 2, 2, 5, 0, 0, 5, 7, ...  
...                                                  ...  
27028  [19, 15, 4, 0, 114, 946, 0, 0, 27, 31, 22, 5, ...  
27029  [0, 50, 60, 110, 3, 3, 12, 17, 0, 50, 13, 27, ...  
27030  [0, 2, 25, 0, 17, 14, 0, 30, 0, 29, 0, 18, 11,...  
27031  [5, 0, 20, 2, 0, 0, 0, 0, 28, 5, 23, 4, 24, 25...  
27032  [66, 20, 0, 21, 51, 4, 0, 22, 52, 16, 26, 23, ...  

[27032 rows x 6 columns]

# Train-Test spliting

In [37]:
from sklearn.model_selection import train_test_split
X = train_updated_group.drop(columns='classes')
y = train_updated_group['classes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [38]:
X_train.head()

Patient-Uid  \
26885  a0f0b8aa-1c7c-11ec-bceb-16262ee38c7f   
3139   a0deedc9-1c7c-11ec-997a-16262ee38c7f   
25384  a0ef9cc9-1c7c-11ec-85ea-16262ee38c7f   
7260   a0e2018f-1c7c-11ec-acf5-16262ee38c7f   
6220   a0e13d1e-1c7c-11ec-8138-16262ee38c7f   

                                                Incident  cutoff_indices  \
26885  TEST_TYPE_1 DRUG_TYPE_0 TEST_TYPE_1 TEST_TYPE_...              50   
3139   DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_...             102   
25384  DRUG_TYPE_7 DRUG_TYPE_7 DRUG_TYPE_7 DRUG_TYPE_...              74   
7260   DRUG_TYPE_6 DRUG_TYPE_6 PRIMARY_DIAGNOSIS TEST...              77   
6220   DRUG_TYPE_2 PRIMARY_DIAGNOSIS DRUG_TYPE_6 DRUG...             134   

                                           Incident_Drug  \
26885  TEST_TYPE_1 DRUG_TYPE_0 TEST_TYPE_1 TEST_TYPE_...   
3139   DRUG_TYPE_0 DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_...   
25384  DRUG_TYPE_7 DRUG_TYPE_7 DRUG_TYPE_7 DRUG_TYPE_...   
7260   DRUG_TYPE_6 DRUG_TYPE_6 PRIMARY_DIAGNOSIS TEST...   
6220   DRUG_TYPE_2 PRIMARY_DIAGNOSIS DRUG_TYPE_6 DRUG...   

                                     Time_based_features  
26885  [23, 217, 4, 11, 0, 0, 21, 0, 2, 24, 42, 8, 76...  
3139   [60, 0, 0, 25, 0, 1, 1, 6, 0, 0, 0, 0, 0, 0, 2...  
25384  [89, 63, 35, 27, 27, 24, 148, 13, 0, 56, 75, 7...  
7260   [41, 16, 0, 1, 44, 38, 0, 5, 10, 34, 48, 0, 5,...  
6220   [232, 93, 0, 0, 0, 0, 0, 36, 24, 39, 23, 18, 1...

# Tokenizing the train data

In [39]:
import tensorflow as tf

tokenizer = tf.keras.preprocessing.text.Tokenizer(filters='',lower=False, split=" ")

#tokenizer on the text data
tokenizer.fit_on_texts(X_train['Incident_Drug'].values)

# text and applying front-side padding
encoded_train= tokenizer.texts_to_sequences(X_train['Incident_Drug'].values)
pad_train= tf.keras.preprocessing.sequence.pad_sequences(encoded_train, padding='pre')

In [40]:
pad_train.shape

(21625, 1645)

In [41]:
for i in pad_train[:]:
    print(i)

[0 0 0 ... 1 4 5]
[0 0 0 ... 2 1 4]
[0 0 0 ... 1 3 8]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 3]
[0 0 0 ... 6 5 5]
[0 0 0 ... 2 3 2]
[ 0  0  0 ...  2  1 10]
[0 0 0 ... 2 2 3]
[ 0  0  0 ... 14  3  9]
[0 0 0 ... 1 1 1]
[0 0 0 ... 8 1 3]
[0 0 0 ... 4 5 4]
[ 0  0  0 ... 11 11 11]
[0 0 0 ... 1 2 3]
[0 0 0 ... 7 4 2]
[ 0  0  0 ...  1  5 10]
[0 0 0 ... 2 4 3]
[ 0  0  0 ... 35 35  5]
[0 0 0 ... 1 1 1]
[0 0 0 ... 7 4 7]
[0 0 0 ... 1 5 3]
[0 0 0 ... 4 4 4]
[ 0  0  0 ...  7  4 11]
[0 0 0 ... 1 1 2]
[0 0 0 ... 6 5 6]
[ 0  0  0 ...  3  9 12]
[0 0 0 ... 1 4 1]
[0 0 0 ... 3 3 1]
[0 0 0 ... 3 2 1]
[0 0 0 ... 6 4 4]
[0 0 0 ... 1 3 1]
[0 0 0 ... 2 2 3]
[0 0 0 ... 5 2 6]
[0 0 0 ... 4 2 7]
[0 0 0 ... 4 6 3]
[0 0 0 ... 1 1 4]
[0 0 0 ... 1 8 3]
[0 0 0 ... 7 4 4]
[ 0  0  0 ... 27  9  1]
[ 0  0  0 ...  1  1 12]
[0 0 0 ... 5 7 7]
[0 0 0 ... 5 5 1]
[0 0 0 ... 1 5 6]
[0 0 0 ... 3 7 3]
[0 0 0 ... 4 1 6]
[0 0 0 ... 4 1 1]
[ 0  0  0 ...  3  9 27]
[0 0 0 ... 2 4 7]
[0 0 0 ... 6 4 8]
[0 0 0 ... 2 2 2]
[ 0  0  0 ...  9 12  5

[0 0 0 ... 2 6 2]
[0 0 0 ... 1 1 4]
[0 0 0 ... 1 6 4]
[ 0  0  0 ...  1  3 25]
[0 0 0 ... 2 2 2]
[ 0  0  0 ... 11  7 28]
[0 0 0 ... 1 4 4]
[0 0 0 ... 7 5 3]
[0 0 0 ... 7 7 7]
[0 0 0 ... 8 3 8]
[0 0 0 ... 6 3 3]
[0 0 0 ... 1 4 5]
[0 0 0 ... 2 1 1]
[0 0 0 ... 1 4 1]
[0 0 0 ... 9 5 9]
[0 0 0 ... 1 5 5]
[0 0 0 ... 3 4 2]
[0 0 0 ... 4 4 4]
[0 0 0 ... 1 3 4]
[ 0  0  0 ... 10  6  1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 3 3 3]
[0 0 0 ... 9 9 4]
[0 0 0 ... 4 8 5]
[0 0 0 ... 4 2 2]
[ 0  0  0 ... 27  9  3]
[0 0 0 ... 2 3 1]
[0 0 0 ... 5 4 2]
[0 0 0 ... 8 1 2]
[0 0 0 ... 7 7 7]
[0 0 0 ... 7 7 7]
[0 0 0 ... 7 2 2]
[ 0  0  0 ...  2 16  2]
[0 0 0 ... 2 2 4]
[0 0 0 ... 3 2 1]
[0 0 0 ... 1 1 4]
[0 0 0 ... 3 3 5]
[0 0 0 ... 4 1 1]
[0 0 0 ... 2 1 7]
[0 0 0 ... 8 2 2]
[0 0 0 ... 4 3 9]
[0 0 0 ... 2 1 4]
[0 0 0 ... 3 3 9]
[ 0  0  0 ... 20 20  7]
[0 0 0 ... 4 5 6]
[ 0  0  0 ...  8  3 42]
[0 0 0 ... 7 2 5]
[ 0  0  0 ... 39  2  2]
[0 0 0 ... 3 7 3]
[0 0 0 ... 2 3 2]
[ 0  0  0 ... 11  1  9]
[0 0 0 ... 4 2 3]
[0 0 0 ...

[0 0 0 ... 1 4 4]
[ 0  0  0 ... 11  5  1]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  3  1 38]
[0 0 0 ... 2 3 3]
[0 0 0 ... 3 7 7]
[0 0 0 ... 4 4 5]
[ 0  0  0 ...  2 18 18]
[ 0  0  0 ...  9 16 16]
[ 0  0  0 ...  3  3 13]
[0 0 0 ... 1 1 9]
[0 0 0 ... 5 5 3]
[0 0 0 ... 3 8 8]
[0 0 0 ... 2 2 2]
[0 0 0 ... 2 6 5]
[0 0 0 ... 2 8 4]
[0 0 0 ... 1 4 6]
[ 0  0  0 ...  1  6 36]
[0 0 0 ... 1 2 2]
[ 0  0  0 ...  9 22 16]
[0 0 0 ... 4 1 4]
[ 0  0  0 ...  3  4 21]
[ 0  0  0 ... 33  4  7]
[0 0 0 ... 4 6 2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 5 5 5]
[0 0 0 ... 2 2 4]
[ 0  0  0 ... 24  9  2]
[0 0 0 ... 2 6 6]
[0 0 0 ... 1 1 1]
[0 0 0 ... 2 1 1]
[ 0  0  0 ...  5 18 18]
[0 0 0 ... 4 1 2]
[0 0 0 ... 2 3 6]
[ 0  0  0 ... 11  7  3]
[0 0 0 ... 3 1 3]
[0 0 0 ... 2 4 2]
[0 0 0 ... 4 5 3]
[ 0  0  0 ...  1 11  4]
[0 0 0 ... 7 2 2]
[ 0  0  0 ...  3 21  3]
[0 0 0 ... 6 7 6]
[ 0  0  0 ...  4 28  4]
[ 0  0  0 ... 11 28  2]
[ 0  0  0 ...  4 15  3]
[0 0 0 ... 4 6 2]
[0 0 0 ... 3 1 3]
[0 0 0 ... 1 1 6]
[0 0 0 ... 2 1 1]
[0 0 0 ... 1 1 1

[0 0 0 ... 3 2 1]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  4 11  9]
[ 0  0  0 ... 22  2  3]
[0 0 0 ... 8 4 7]
[0 0 0 ... 7 2 7]
[0 0 0 ... 2 3 2]
[0 0 0 ... 2 2 1]
[0 0 0 ... 3 6 3]
[0 0 0 ... 3 2 8]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[ 0  0  0 ... 13 12  9]
[0 0 0 ... 8 8 1]
[ 0  0  0 ... 18  2 18]
[ 0  0  0 ... 10  6 10]
[ 0  0  0 ...  1  1 35]
[ 0  0  0 ...  4 13  6]
[ 0  0  0 ...  6 10  4]
[0 0 0 ... 3 7 3]
[0 0 0 ... 1 5 3]
[0 0 0 ... 2 2 2]
[0 0 0 ... 4 7 4]
[0 0 0 ... 1 1 2]
[0 0 0 ... 3 2 1]
[0 0 0 ... 2 8 1]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  5 11  1]
[0 0 0 ... 5 9 6]
[0 0 0 ... 4 2 2]
[0 0 0 ... 4 6 7]
[ 0  0  0 ... 11 24  5]
[0 0 0 ... 4 4 4]
[0 0 0 ... 8 5 8]
[ 0  0  0 ... 18  4 18]
[0 0 0 ... 7 7 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 8 8 2]
[ 0  0  0 ... 15  5  6]
[0 0 0 ... 1 3 3]
[0 0 0 ... 5 5 9]
[0 0 0 ... 1 3 2]
[0 0 0 ... 6 1 8]
[ 0  0  0 ... 12  9  9]
[0 0 0 ... 1 8 2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 7 7 4]
[0 0 0 ... 8 8 5]
[0 0 0 ... 1 1 1]
[ 0  0  0 ... 10  3  3]
[0 0 0 ... 4 1 1

[0 0 0 ... 3 6 2]
[0 0 0 ... 8 9 1]
[ 0  0  0 ...  4  6 11]
[0 0 0 ... 5 5 5]
[0 0 0 ... 4 2 1]
[ 0  0  0 ... 18 18 18]
[0 0 0 ... 6 5 5]
[ 0  0  0 ...  5 32  3]
[0 0 0 ... 1 6 1]
[0 0 0 ... 4 1 1]
[0 0 0 ... 3 1 1]
[0 0 0 ... 1 3 1]
[0 0 0 ... 4 8 4]
[ 0  0  0 ...  1 28  2]
[ 0  0  0 ...  4  4 13]
[0 0 0 ... 3 4 3]
[ 0  0  0 ...  2 12  1]
[0 0 0 ... 1 1 8]
[ 0  0  0 ...  4 11  2]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  1  1 39]
[ 0  0  0 ...  9 12  6]
[0 0 0 ... 1 4 1]
[ 0  0  0 ... 11 11 11]
[ 0  0  0 ...  3  4 18]
[ 0  0  0 ... 30  2  9]
[0 0 0 ... 3 3 1]
[0 0 0 ... 3 3 3]
[0 0 0 ... 4 4 4]
[0 0 0 ... 1 2 1]
[0 0 0 ... 1 2 3]
[ 0  0  0 ...  4  4 11]
[ 0  0  0 ...  2  2 18]
[0 0 0 ... 1 1 1]
[0 0 0 ... 8 1 1]
[0 0 0 ... 1 1 9]
[0 0 0 ... 4 4 4]
[ 0  0  0 ...  6 10  6]
[ 0  0  0 ...  7 12  7]
[0 0 0 ... 2 2 5]
[0 0 0 ... 1 8 2]
[0 0 0 ... 1 2 5]
[ 0  0  0 ...  1 18 18]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 4]
[ 0  0  0 ... 18  3  8]
[ 0  0  0 ...  5 11 11]
[0 0 0 ... 9 7 2]
[0 0 0 ... 2 7 4]
[ 0 

[0 0 0 ... 1 1 1]
[0 0 0 ... 7 2 2]
[0 0 0 ... 7 4 2]
[0 0 0 ... 1 2 1]
[0 0 0 ... 1 1 2]
[ 0  0  0 ...  6 12  9]
[0 0 0 ... 8 6 8]
[0 0 0 ... 1 4 1]
[0 0 0 ... 2 7 7]
[0 0 0 ... 6 3 9]
[0 0 0 ... 6 4 6]
[ 0  0  0 ...  2 18  2]
[ 0  0  0 ... 13  5 34]
[0 0 0 ... 8 1 1]
[0 0 0 ... 1 6 2]
[0 0 0 ... 8 1 3]
[0 0 0 ... 1 2 4]
[0 0 0 ... 3 3 3]
[ 0  0  0 ... 20  7  3]
[0 0 0 ... 1 5 1]
[0 0 0 ... 4 3 4]
[ 0  0  0 ...  5 28  3]
[0 0 0 ... 6 5 4]
[0 0 0 ... 1 4 1]
[0 0 0 ... 1 7 6]
[ 0  0  0 ...  4  4 18]
[0 0 0 ... 9 4 4]
[0 0 0 ... 4 4 4]
[0 0 0 ... 8 6 6]
[ 0  0  0 ... 11  9  5]
[0 0 0 ... 4 4 4]
[ 0  0  0 ... 13 21 21]
[0 0 0 ... 3 1 6]
[0 0 0 ... 1 1 1]
[0 0 0 ... 8 2 8]
[0 0 0 ... 1 1 1]
[0 0 0 ... 6 1 6]
[0 0 0 ... 2 7 7]
[0 0 0 ... 2 3 8]
[0 0 0 ... 2 4 3]
[0 0 0 ... 3 2 2]
[0 0 0 ... 4 3 4]
[ 0  0  0 ...  3  7 11]
[0 0 0 ... 1 1 1]
[0 0 0 ... 3 3 2]
[ 0  0  0 ...  6  5 33]
[0 0 0 ... 9 9 2]
[0 0 0 ... 2 2 2]
[0 0 0 ... 1 1 3]
[0 0 0 ... 2 8 3]
[0 0 0 ... 1 8 4]
[0 0 0 ... 6 5 1]
[0 0

[0 0 0 ... 3 6 2]
[0 0 0 ... 1 2 3]
[0 0 0 ... 2 3 8]
[0 0 0 ... 1 1 4]
[ 0  0  0 ... 12  3  3]
[0 0 0 ... 4 4 4]
[0 0 0 ... 7 7 7]
[0 0 0 ... 1 3 2]
[0 0 0 ... 1 3 1]
[0 0 0 ... 7 7 7]
[0 0 0 ... 5 1 1]
[0 0 0 ... 2 4 1]
[0 0 0 ... 4 6 5]
[0 0 0 ... 3 1 4]
[0 0 0 ... 6 5 5]
[0 0 0 ... 2 1 1]
[0 0 0 ... 2 4 2]
[0 0 0 ... 3 1 5]
[0 0 0 ... 1 1 8]
[0 0 0 ... 3 1 2]
[ 0  0  0 ... 17 17 17]
[ 0  0  0 ... 18  6  6]
[0 0 0 ... 4 1 1]
[ 0  0  0 ...  2  2 11]
[0 0 0 ... 3 3 3]
[0 0 0 ... 4 2 1]
[0 0 0 ... 2 1 1]
[0 0 0 ... 3 3 3]
[ 0  0  0 ...  6  2 18]
[0 0 0 ... 2 1 3]
[0 0 0 ... 2 1 5]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  6 18  2]
[ 0  0  0 ...  9  3 37]
[ 0  0  0 ...  3  1 39]
[0 0 0 ... 1 1 1]
[0 0 0 ... 3 1 8]
[0 0 0 ... 2 4 4]
[0 0 0 ... 5 1 4]
[0 0 0 ... 3 9 6]
[ 0  0  0 ... 10  4  3]
[ 0  0  0 ... 15  6  1]
[0 0 0 ... 2 2 2]
[ 0  0  0 ...  3  3 11]
[0 0 0 ... 3 6 7]
[ 0  0  0 ... 38  4 11]
[0 0 0 ... 5 1 2]
[0 0 0 ... 4 6 1]
[0 0 0 ... 7 7 6]
[0 0 0 ... 3 1 2]
[0 0 0 ... 7 7 7]
[0 0 0 ...

[0 0 0 ... 2 1 2]
[0 0 0 ... 2 2 5]
[ 0  0  0 ...  2  5 11]
[0 0 0 ... 1 1 2]
[0 0 0 ... 4 1 1]
[0 0 0 ... 7 2 4]
[0 0 0 ... 1 2 1]
[0 0 0 ... 6 5 8]
[0 0 0 ... 2 4 7]
[ 0  0  0 ...  2  3 18]
[0 0 0 ... 5 8 2]
[0 0 0 ... 3 2 5]
[0 0 0 ... 1 1 1]
[ 0  0  0 ... 18 18 18]
[0 0 0 ... 1 4 1]
[ 0  0  0 ...  1  6 37]
[0 0 0 ... 6 5 5]
[0 0 0 ... 3 5 5]
[ 0  0  0 ...  9  5 11]
[ 0  0  0 ...  3  9 27]
[0 0 0 ... 1 2 7]
[0 0 0 ... 2 1 2]
[0 0 0 ... 2 2 2]
[0 0 0 ... 4 5 5]
[0 0 0 ... 2 1 1]
[0 0 0 ... 1 4 3]
[ 0  0  0 ... 33 33 33]
[0 0 0 ... 1 2 1]
[0 0 0 ... 4 7 4]
[ 0  0  0 ... 14  5 12]
[0 0 0 ... 1 2 1]
[0 0 0 ... 2 8 4]
[0 0 0 ... 4 5 5]
[0 0 0 ... 6 3 6]
[0 0 0 ... 7 3 7]
[0 0 0 ... 4 4 6]
[0 0 0 ... 1 2 5]
[0 0 0 ... 5 3 1]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  9 16  4]
[ 0  0  0 ...  4 18  4]
[0 0 0 ... 7 4 7]
[0 0 0 ... 2 7 7]
[0 0 0 ... 3 2 1]
[0 0 0 ... 3 4 1]
[ 0  0  0 ...  9 49  9]
[0 0 0 ... 4 8 1]
[0 0 0 ... 3 3 1]
[0 0 0 ... 7 7 7]
[0 0 0 ... 5 1 4]
[0 0 0 ... 5 2 6]
[0 0 0 ... 2 2 3

[0 0 0 ... 7 7 7]
[0 0 0 ... 4 2 2]
[0 0 0 ... 9 5 2]
[0 0 0 ... 2 4 2]
[ 0  0  0 ... 18  4  4]
[ 0  0  0 ... 18  6  4]
[ 0  0  0 ... 21 14 13]
[0 0 0 ... 6 6 2]
[ 0  0  0 ... 36  1  4]
[0 0 0 ... 2 1 2]
[0 0 0 ... 2 1 4]
[ 0  0  0 ... 11  7  8]
[0 0 0 ... 5 6 2]
[ 0  0  0 ...  2 11 11]
[0 0 0 ... 3 3 3]
[0 0 0 ... 8 1 1]
[ 0  0  0 ...  1  2 10]
[0 0 0 ... 4 2 7]
[ 0  0  0 ...  4 28  4]
[0 0 0 ... 1 8 4]
[0 0 0 ... 3 8 1]
[0 0 0 ... 2 1 1]
[0 0 0 ... 1 8 2]
[ 0  0  0 ...  4  5 16]
[0 0 0 ... 2 1 1]
[0 0 0 ... 1 6 1]
[ 0  0  0 ...  1 10  1]
[0 0 0 ... 8 1 8]
[0 0 0 ... 1 3 6]
[0 0 0 ... 2 3 5]
[0 0 0 ... 2 6 1]
[0 0 0 ... 4 2 4]
[0 0 0 ... 6 4 4]
[0 0 0 ... 3 2 3]
[0 0 0 ... 7 7 7]
[ 0  0  0 ...  2 11  8]
[0 0 0 ... 1 1 3]
[0 0 0 ... 9 5 5]
[0 0 0 ... 2 3 7]
[0 0 0 ... 1 5 1]
[0 0 0 ... 4 8 2]
[ 0  0  0 ...  5  5 25]
[ 0  0  0 ...  4  1 26]
[0 0 0 ... 4 4 1]
[ 0  0  0 ... 14 14  5]
[ 0  0  0 ... 16  3  5]
[0 0 0 ... 4 1 4]
[0 0 0 ... 1 2 2]
[ 0  0  0 ... 18  4 18]
[0 0 0 ... 9 3 9]
[0 0

[0 0 0 ... 2 5 5]
[ 0  0  0 ... 18 18  2]
[ 0  0  0 ...  3 10  8]
[ 0  0  0 ... 25 22 35]
[0 0 0 ... 8 3 2]
[0 0 0 ... 4 1 5]
[0 0 0 ... 3 3 1]
[ 0  0  0 ...  4 18 16]
[0 0 0 ... 4 8 1]
[ 0  0  0 ... 33 33  5]
[0 0 0 ... 2 2 2]
[ 0  0  0 ...  4 10  4]
[0 0 0 ... 3 1 1]
[ 0  0  0 ...  2  5 18]
[0 0 0 ... 2 1 2]
[0 0 0 ... 4 4 4]
[0 0 0 ... 3 5 1]
[ 0  0  0 ... 11  1  2]
[0 0 0 ... 1 5 2]
[ 0  0  0 ...  3  3 24]
[ 0  0  0 ... 10  6  1]
[ 0  0  0 ...  3  1 25]
[0 0 0 ... 1 2 3]
[0 0 0 ... 6 4 1]
[0 0 0 ... 7 1 6]
[0 0 0 ... 1 1 7]
[ 0  0  0 ...  7  9 11]
[0 0 0 ... 6 5 5]
[ 0  0  0 ...  4 21  1]
[0 0 0 ... 2 2 2]
[0 0 0 ... 3 8 3]
[0 0 0 ... 1 2 2]
[0 0 0 ... 1 6 6]
[0 0 0 ... 3 3 3]
[0 0 0 ... 6 2 2]
[0 0 0 ... 9 1 3]
[0 0 0 ... 6 6 6]
[0 0 0 ... 6 4 4]
[0 0 0 ... 3 6 2]
[0 0 0 ... 4 5 4]
[0 0 0 ... 6 7 7]
[0 0 0 ... 4 8 1]
[0 0 0 ... 2 4 1]
[ 0  0  0 ... 10  3 10]
[0 0 0 ... 2 4 1]
[ 0  0  0 ...  2  4 11]
[0 0 0 ... 3 8 6]
[0 0 0 ... 7 2 5]
[ 0  0  0 ...  5 11 11]
[0 0 0 ... 3 2 4]
[ 0 

[ 0  0  0 ... 34  9 25]
[ 0  0  0 ...  3 10  7]
[ 0  0  0 ... 10  6 10]
[ 0  0  0 ... 14 12 17]
[0 0 0 ... 6 6 1]
[0 0 0 ... 1 2 3]
[0 0 0 ... 2 4 2]
[0 0 0 ... 8 1 8]
[0 0 0 ... 7 5 6]
[ 0  0  0 ... 11 25  5]
[ 0  0  0 ... 30  5  5]
[ 0  0  0 ... 17 17 17]
[0 0 0 ... 1 3 4]
[0 0 0 ... 4 4 4]
[0 0 0 ... 3 9 9]
[0 0 0 ... 1 2 3]
[ 0  0  0 ... 11  2  2]
[0 0 0 ... 2 1 1]
[0 0 0 ... 4 4 4]
[0 0 0 ... 2 1 2]
[0 0 0 ... 4 9 3]
[0 0 0 ... 7 5 4]
[0 0 0 ... 3 6 3]
[0 0 0 ... 4 1 2]
[ 0  0  0 ...  4  7 11]
[ 0  0  0 ...  3  9 27]
[0 0 0 ... 6 2 1]
[ 0  0  0 ...  2 10  6]
[ 0  0  0 ... 18  6  3]
[0 0 0 ... 7 4 1]
[ 0  0  0 ... 18  1  2]
[0 0 0 ... 1 3 1]
[ 0  0  0 ... 19  1 19]
[ 0  0  0 ... 11  9 11]
[0 0 0 ... 2 4 4]
[0 0 0 ... 1 1 4]
[ 0  0  0 ...  1 10  8]
[0 0 0 ... 1 4 2]
[0 0 0 ... 3 1 3]
[ 0  0  0 ...  5 19  4]
[ 0  0  0 ...  8  1 16]
[0 0 0 ... 5 5 9]
[0 0 0 ... 2 6 4]
[0 0 0 ... 7 3 8]
[ 0  0  0 ...  5 13 14]
[0 0 0 ... 5 3 3]
[ 0  0  0 ...  6 13  6]
[0 0 0 ... 2 2 2]
[0 0 0 ... 3 4 1

[0 0 0 ... 9 9 9]
[0 0 0 ... 7 3 4]
[0 0 0 ... 4 6 8]
[0 0 0 ... 7 7 7]
[ 0  0  0 ... 18 10  1]
[0 0 0 ... 6 2 4]
[0 0 0 ... 4 7 3]
[0 0 0 ... 8 4 2]
[0 0 0 ... 1 1 2]
[0 0 0 ... 5 6 6]
[0 0 0 ... 7 2 2]
[0 0 0 ... 1 5 6]
[0 0 0 ... 4 1 1]
[0 0 0 ... 4 2 2]
[0 0 0 ... 1 9 1]
[0 0 0 ... 8 4 6]
[0 0 0 ... 5 5 1]
[0 0 0 ... 3 9 9]
[0 0 0 ... 2 2 1]
[0 0 0 ... 3 3 3]
[0 0 0 ... 1 8 8]
[0 0 0 ... 4 5 4]
[0 0 0 ... 2 2 5]
[ 0  0  0 ...  3 36  4]
[0 0 0 ... 4 2 2]
[0 0 0 ... 1 1 9]
[0 0 0 ... 8 1 4]
[ 0  0  0 ... 11  2  1]
[ 0  0  0 ... 17 17 17]
[0 0 0 ... 1 4 2]
[0 0 0 ... 6 3 1]
[0 0 0 ... 3 6 4]
[ 0  0  0 ... 28 11 11]
[0 0 0 ... 8 8 1]
[0 0 0 ... 7 2 5]
[ 0  0  0 ... 10  1 10]
[0 0 0 ... 1 3 3]
[0 0 0 ... 2 3 2]
[0 0 0 ... 4 2 2]
[ 0  0  0 ...  9 37 23]
[0 0 0 ... 4 4 6]
[0 0 0 ... 4 2 1]
[0 0 0 ... 9 8 5]
[0 0 0 ... 3 9 3]
[0 0 0 ... 6 3 4]
[ 0  0  0 ...  4  4 11]
[0 0 0 ... 2 4 2]
[0 0 0 ... 5 3 1]
[0 0 0 ... 7 2 7]
[0 0 0 ... 7 7 7]
[0 0 0 ... 3 1 5]
[0 0 0 ... 2 1 2]
[0 0 0 ... 9 7 7

[0 0 0 ... 5 4 2]
[0 0 0 ... 2 2 2]
[0 0 0 ... 5 2 6]
[0 0 0 ... 9 1 4]
[ 0  0  0 ... 12 10  2]
[ 0  0  0 ... 12  6  9]
[ 0  0  0 ...  5  1 21]
[0 0 0 ... 3 1 4]
[ 0  0  0 ...  1 25  1]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  4 18 18]
[0 0 0 ... 1 1 4]
[0 0 0 ... 7 3 4]
[0 0 0 ... 7 2 2]
[ 0  0  0 ...  3 27 18]
[0 0 0 ... 2 2 4]
[0 0 0 ... 3 1 4]
[0 0 0 ... 3 1 3]
[0 0 0 ... 1 3 1]
[0 0 0 ... 2 3 4]
[0 0 0 ... 8 1 3]
[ 0  0  0 ...  3 12 12]
[ 0  0  0 ... 29 29 30]
[0 0 0 ... 1 2 2]
[0 0 0 ... 4 6 6]
[ 0  0  0 ... 11 28  4]
[0 0 0 ... 3 3 1]
[0 0 0 ... 3 6 6]
[ 0  0  0 ... 10  4 10]
[0 0 0 ... 1 1 1]
[0 0 0 ... 2 1 2]
[0 0 0 ... 6 5 2]
[0 0 0 ... 4 1 1]
[0 0 0 ... 4 5 4]
[0 0 0 ... 1 1 2]
[0 0 0 ... 4 5 2]
[0 0 0 ... 2 2 2]
[0 0 0 ... 4 4 8]
[0 0 0 ... 4 2 1]
[0 0 0 ... 3 3 1]
[ 0  0  0 ... 36 36  4]
[0 0 0 ... 2 1 4]
[ 0  0  0 ...  5 10  5]
[ 0  0  0 ... 11 11  2]
[ 0  0  0 ...  5 42  5]
[0 0 0 ... 5 4 6]
[0 0 0 ... 1 1 1]
[0 0 0 ... 7 7 4]
[0 0 0 ... 2 1 1]
[0 0 0 ... 1 4 4]
[0 0 0 ... 1 2 1

[0 0 0 ... 2 1 1]
[0 0 0 ... 7 7 2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 2 7 1]
[ 0  0  0 ... 19  7  7]
[ 0  0  0 ...  1 11  6]
[0 0 0 ... 8 3 3]
[0 0 0 ... 5 5 5]
[ 0  0  0 ... 18 18  4]
[0 0 0 ... 1 2 1]
[ 0  0  0 ...  1 11  1]
[0 0 0 ... 2 4 4]
[0 0 0 ... 9 1 1]
[0 0 0 ... 7 1 6]
[0 0 0 ... 4 2 7]
[0 0 0 ... 7 7 7]
[0 0 0 ... 1 2 9]
[0 0 0 ... 3 6 4]
[ 0  0  0 ...  6 35  9]
[ 0  0  0 ... 31  2  7]
[0 0 0 ... 1 1 1]
[ 0  0  0 ... 18  5 18]
[ 0  0  0 ... 15 12  3]
[ 0  0  0 ... 10  1  8]
[0 0 0 ... 3 6 3]
[0 0 0 ... 4 4 8]
[ 0  0  0 ... 24  5 30]
[0 0 0 ... 3 4 9]
[0 0 0 ... 1 2 6]
[ 0  0  0 ... 18  5  3]
[0 0 0 ... 4 1 1]
[ 0  0  0 ...  4 13  5]
[0 0 0 ... 3 3 3]
[0 0 0 ... 1 5 5]
[0 0 0 ... 4 5 4]
[ 0  0  0 ... 23  5 11]
[0 0 0 ... 7 5 5]
[0 0 0 ... 2 2 4]
[0 0 0 ... 3 3 6]
[0 0 0 ... 1 5 6]
[0 0 0 ... 5 4 5]
[0 0 0 ... 1 4 8]
[0 0 0 ... 2 2 2]
[0 0 0 ... 2 6 6]
[0 0 0 ... 4 3 4]
[0 0 0 ... 1 3 3]
[0 0 0 ... 4 1 1]
[0 0 0 ... 1 2 3]
[ 0  0  0 ... 16  6  5]
[0 0 0 ... 2 1 5]
[0 0 0 ... 4 4 3

[0 0 0 ... 6 2 4]
[0 0 0 ... 3 1 8]
[ 0  0  0 ...  2  6 10]
[ 0  0  0 ...  2 10  4]
[0 0 0 ... 2 2 2]
[ 0  0  0 ... 22 18 18]
[0 0 0 ... 5 1 4]
[0 0 0 ... 8 4 1]
[0 0 0 ... 7 7 7]
[ 0  0  0 ...  4 11 11]
[0 0 0 ... 8 6 3]
[0 0 0 ... 4 1 4]
[ 0  0  0 ... 18  2 18]
[0 0 0 ... 3 3 2]
[ 0  0  0 ...  2 11  2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 2 2 2]
[0 0 0 ... 3 3 3]
[0 0 0 ... 3 3 6]
[0 0 0 ... 8 8 1]
[0 0 0 ... 4 5 5]
[0 0 0 ... 5 3 5]
[0 0 0 ... 2 4 4]
[ 0  0  0 ... 11  1  1]
[ 0  0  0 ...  5 18  5]
[0 0 0 ... 6 4 7]
[0 0 0 ... 7 6 4]
[0 0 0 ... 6 3 2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 4 1 1]
[ 0  0  0 ...  3 12  6]
[ 0  0  0 ... 10  1  1]
[0 0 0 ... 2 5 1]
[0 0 0 ... 3 3 6]
[0 0 0 ... 2 2 3]
[ 0  0  0 ...  3  4 11]
[ 0  0  0 ...  6  2 18]
[0 0 0 ... 4 4 4]
[0 0 0 ... 1 2 1]
[0 0 0 ... 7 3 5]
[0 0 0 ... 3 3 3]
[0 0 0 ... 1 4 4]
[0 0 0 ... 6 1 4]
[0 0 0 ... 7 7 7]
[0 0 0 ... 4 2 4]
[ 0  0  0 ...  5 12  5]
[ 0  0  0 ...  1  1 11]
[0 0 0 ... 7 7 4]
[ 0  0  0 ... 11  2  1]
[0 0 0 ... 4 4 3]
[ 0  0  0 

[0 0 0 ... 1 2 1]
[0 0 0 ... 1 2 4]
[ 0  0  0 ... 13  1 32]
[ 0  0  0 ... 18 18  5]
[ 0  0  0 ...  3 12  3]
[0 0 0 ... 5 5 5]
[0 0 0 ... 1 2 1]
[ 0  0  0 ...  8 12  2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 9 4 1]
[0 0 0 ... 7 7 7]
[0 0 0 ... 2 2 2]
[ 0  0  0 ... 10  6  4]
[0 0 0 ... 3 8 6]
[0 0 0 ... 6 2 4]
[0 0 0 ... 6 6 2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 2 3 2]
[0 0 0 ... 1 2 1]
[ 0  0  0 ...  4 27  4]
[0 0 0 ... 1 8 3]
[0 0 0 ... 7 2 7]
[0 0 0 ... 1 1 2]
[0 0 0 ... 3 3 2]
[ 0  0  0 ...  2  5 14]
[0 0 0 ... 6 5 7]
[0 0 0 ... 1 5 3]
[0 0 0 ... 3 6 2]
[0 0 0 ... 7 7 4]
[ 0  0  0 ... 11 28 42]
[0 0 0 ... 1 1 2]
[ 0  0  0 ...  5 11 28]
[ 0  0  0 ...  3 12  5]
[0 0 0 ... 8 2 1]
[0 0 0 ... 7 7 4]
[0 0 0 ... 3 1 8]
[0 0 0 ... 5 5 6]
[0 0 0 ... 7 1 7]
[ 0  0  0 ...  6  6 10]
[0 0 0 ... 4 4 1]
[0 0 0 ... 2 9 2]
[0 0 0 ... 1 1 4]
[0 0 0 ... 6 3 3]
[0 0 0 ... 1 1 2]
[ 0  0  0 ... 29  1 18]
[0 0 0 ... 3 1 8]
[0 0 0 ... 6 5 5]
[0 0 0 ... 7 2 7]
[0 0 0 ... 1 5 8]
[0 0 0 ... 2 5 2]
[ 0  0  0 ... 10  1  1]
[0 0

[0 0 0 ... 2 8 1]
[0 0 0 ... 1 6 1]
[0 0 0 ... 4 1 1]
[ 0  0  0 ... 25  6 10]
[0 0 0 ... 9 2 6]
[0 0 0 ... 6 5 1]
[0 0 0 ... 2 4 6]
[0 0 0 ... 3 6 4]
[ 0  0  0 ...  3 12  3]
[0 0 0 ... 6 5 1]
[0 0 0 ... 4 3 4]
[0 0 0 ... 5 1 2]
[0 0 0 ... 3 1 4]
[ 0  0  0 ... 18  3  4]
[0 0 0 ... 5 1 1]
[ 0  0  0 ...  2  2 22]
[ 0  0  0 ...  3 32 32]
[0 0 0 ... 2 3 2]
[0 0 0 ... 4 6 8]
[0 0 0 ... 4 4 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 2 2 2]
[0 0 0 ... 1 2 5]
[0 0 0 ... 4 1 2]
[0 0 0 ... 8 2 9]
[0 0 0 ... 5 6 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 4 4 6]
[0 0 0 ... 8 2 3]
[0 0 0 ... 2 6 1]
[ 0  0  0 ...  1  8 10]
[0 0 0 ... 2 3 3]
[0 0 0 ... 7 3 9]
[0 0 0 ... 7 3 4]
[0 0 0 ... 1 2 1]
[ 0  0  0 ... 10  7  1]
[ 0  0  0 ... 10 36  4]
[0 0 0 ... 1 2 8]
[0 0 0 ... 1 4 2]
[ 0  0  0 ... 10  7  7]
[0 0 0 ... 6 8 6]
[0 0 0 ... 2 7 6]
[ 0  0  0 ... 14  4  8]
[0 0 0 ... 2 1 2]
[0 0 0 ... 3 1 3]
[0 0 0 ... 7 7 7]
[ 0  0  0 ...  9 18 18]
[0 0 0 ... 6 3 6]
[0 0 0 ... 4 5 5]
[0 0 0 ... 6 5 6]
[0 0 0 ... 4 9 2]
[0 0 0 ... 6 4 2

[0 0 0 ... 3 3 1]
[0 0 0 ... 3 6 4]
[0 0 0 ... 8 1 2]
[0 0 0 ... 1 4 4]
[0 0 0 ... 2 3 3]
[ 0  0  0 ...  1 11  1]
[0 0 0 ... 1 2 1]
[0 0 0 ... 2 2 2]
[ 0  0  0 ...  5  2 14]
[0 0 0 ... 6 3 6]
[0 0 0 ... 5 8 3]
[0 0 0 ... 8 5 3]
[0 0 0 ... 1 3 4]
[0 0 0 ... 2 1 2]
[0 0 0 ... 1 1 4]
[ 0  0  0 ...  8  2 11]
[0 0 0 ... 7 9 2]
[ 0  0  0 ... 11 11 11]
[ 0  0  0 ...  1 16  1]
[0 0 0 ... 5 6 6]
[0 0 0 ... 7 7 7]
[ 0  0  0 ...  2 18  8]
[0 0 0 ... 5 5 6]
[ 0  0  0 ...  4 14  6]
[0 0 0 ... 1 1 1]
[0 0 0 ... 8 4 2]
[0 0 0 ... 4 1 4]
[0 0 0 ... 6 2 8]
[0 0 0 ... 6 6 5]
[ 0  0  0 ... 11  2  1]
[ 0  0  0 ...  2  6 16]
[0 0 0 ... 3 2 2]
[0 0 0 ... 3 5 3]
[0 0 0 ... 1 2 3]
[0 0 0 ... 5 4 2]
[0 0 0 ... 1 2 2]
[0 0 0 ... 4 1 4]
[0 0 0 ... 2 1 3]
[0 0 0 ... 2 2 5]
[0 0 0 ... 1 2 4]
[0 0 0 ... 2 2 2]
[0 0 0 ... 6 6 6]
[ 0  0  0 ...  5 10  5]
[0 0 0 ... 1 9 4]
[ 0  0  0 ... 13  2 13]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  2 19  5]
[0 0 0 ... 5 6 1]
[0 0 0 ... 1 2 2]
[0 0 0 ... 3 2 1]
[ 0  0  0 ... 17  4  2]
[0 0

[0 0 0 ... 2 1 1]
[0 0 0 ... 2 1 2]
[ 0  0  0 ... 20  7  7]
[0 0 0 ... 8 1 6]
[0 0 0 ... 7 4 7]
[0 0 0 ... 4 1 1]
[0 0 0 ... 2 2 2]
[0 0 0 ... 9 3 1]
[ 0  0  0 ...  1  2 11]
[0 0 0 ... 2 3 3]
[ 0  0  0 ... 18 10  2]
[0 0 0 ... 7 6 1]
[ 0  0  0 ... 18 18  5]
[0 0 0 ... 7 7 7]
[0 0 0 ... 5 9 2]
[ 0  0  0 ... 10  8  2]
[ 0  0  0 ...  4 11 28]
[0 0 0 ... 2 2 2]
[0 0 0 ... 1 4 5]
[ 0  0  0 ...  2  3 12]
[ 0  0  0 ...  7 14  3]
[0 0 0 ... 1 4 3]
[0 0 0 ... 8 2 1]
[0 0 0 ... 1 9 9]
[0 0 0 ... 7 7 3]
[ 0  0  0 ... 13 30 13]
[0 0 0 ... 1 3 4]
[0 0 0 ... 3 1 8]
[0 0 0 ... 5 1 1]
[0 0 0 ... 7 2 7]
[0 0 0 ... 3 4 4]
[0 0 0 ... 1 8 2]
[ 0  0  0 ...  1  4 18]
[0 0 0 ... 3 6 5]
[0 0 0 ... 1 3 1]
[ 0  0  0 ... 26 26 26]
[0 0 0 ... 1 1 5]
[0 0 0 ... 6 1 6]
[0 0 0 ... 2 5 2]
[0 0 0 ... 2 4 2]
[0 0 0 ... 2 1 1]
[ 0  0  0 ...  3 28 11]
[0 0 0 ... 6 8 6]
[ 0  0  0 ... 15 36 10]
[0 0 0 ... 3 3 3]
[0 0 0 ... 8 8 8]
[ 0  0  0 ... 18  2 18]
[0 0 0 ... 3 1 3]
[ 0  0  0 ...  3  9 13]
[0 0 0 ... 9 2 3]
[ 0  0  0 

[ 0  0  0 ...  8 12 11]
[ 0  0  0 ...  1  4 39]
[ 0  0  0 ...  2  6 33]
[0 0 0 ... 1 1 3]
[0 0 0 ... 1 3 4]
[0 0 0 ... 7 7 5]
[0 0 0 ... 1 1 4]
[0 0 0 ... 1 4 2]
[0 0 0 ... 8 6 6]
[0 0 0 ... 3 3 3]
[ 0  0  0 ... 18 18 18]
[ 0  0  0 ... 12 16 16]
[ 0  0  0 ... 15  6  4]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  4  3 11]
[ 0  0  0 ...  6  6 36]
[0 0 0 ... 5 4 4]
[0 0 0 ... 3 3 3]
[ 0  0  0 ...  9  3 12]
[0 0 0 ... 4 4 2]
[0 0 0 ... 5 9 5]
[0 0 0 ... 4 4 4]
[0 0 0 ... 1 1 6]
[0 0 0 ... 1 2 6]
[0 0 0 ... 4 1 1]
[ 0  0  0 ... 12  2  7]
[0 0 0 ... 7 4 7]
[0 0 0 ... 2 2 2]
[ 0  0  0 ...  3 19  4]
[ 0  0  0 ...  2 19  2]
[0 0 0 ... 2 6 4]
[0 0 0 ... 4 2 4]
[0 0 0 ... 4 1 2]
[0 0 0 ... 3 2 2]
[0 0 0 ... 2 2 3]
[0 0 0 ... 3 1 8]
[0 0 0 ... 7 1 2]
[0 0 0 ... 4 7 5]
[0 0 0 ... 1 8 8]
[ 0  0  0 ... 18  4 18]
[0 0 0 ... 3 4 7]
[0 0 0 ... 7 4 7]
[0 0 0 ... 4 4 1]
[0 0 0 ... 2 4 6]
[0 0 0 ... 4 6 4]
[0 0 0 ... 1 1 2]
[ 0  0  0 ...  3 10  3]
[ 0  0  0 ... 21  3  3]
[0 0 0 ... 4 2 8]
[ 0  0  0 ...  2 12 14]
[ 0 

[0 0 0 ... 9 1 1]
[ 0  0  0 ... 11  5  5]
[0 0 0 ... 4 2 2]
[ 0  0  0 ...  5 19  4]
[0 0 0 ... 1 2 1]
[0 0 0 ... 4 5 5]
[0 0 0 ... 1 4 1]
[0 0 0 ... 1 8 1]
[ 0  0  0 ... 25 26  9]
[0 0 0 ... 3 4 6]
[0 0 0 ... 2 1 8]
[ 0  0  0 ...  9  5 21]
[0 0 0 ... 1 4 1]
[0 0 0 ... 7 2 7]
[ 0  0  0 ... 34  4  4]
[0 0 0 ... 5 4 8]
[ 0  0  0 ... 11 11  2]
[0 0 0 ... 1 1 1]
[0 0 0 ... 4 2 2]
[ 0  0  0 ...  2 18  2]
[0 0 0 ... 2 2 6]
[0 0 0 ... 2 1 2]
[0 0 0 ... 1 3 1]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 6 4]
[0 0 0 ... 3 2 4]
[0 0 0 ... 1 2 1]
[0 0 0 ... 1 1 1]
[ 0  0  0 ...  8 36  6]
[0 0 0 ... 1 3 6]
[0 0 0 ... 5 3 5]
[0 0 0 ... 2 2 2]
[0 0 0 ... 3 1 3]
[0 0 0 ... 7 7 5]
[0 0 0 ... 1 8 4]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 2 4]
[0 0 0 ... 3 3 2]
[0 0 0 ... 5 5 8]
[0 0 0 ... 2 4 3]
[ 0  0  0 ...  6  4 11]
[ 0  0  0 ...  1 35 38]
[0 0 0 ... 7 3 4]
[0 0 0 ... 8 8 8]
[0 0 0 ... 8 5 6]
[0 0 0 ... 4 2 1]
[0 0 0 ... 1 1 8]
[0 0 0 ... 2 6 2]
[0 0 0 ... 1 2 3]
[ 0  0  0 ... 12  2 12]
[0 0 0 ... 2 1 2]
[0 0 0 ... 3 5 6

In [42]:
# Encoding the text and applying front-side padding
encoded_test = tokenizer.texts_to_sequences(X_test['Incident_Drug'].values)
pad_test = tf.keras.preprocessing.sequence.pad_sequences(encoded_test, padding='pre', maxlen=1645)

In [43]:
pad_test.shape

(5407, 1645)

In [44]:
pad_test

array([[ 0,  0,  0, ...,  5,  5,  2],
       [ 0,  0,  0, ...,  1, 10, 10],
       [ 0,  0,  0, ...,  8,  6, 10],
       ...,
       [ 0,  0,  0, ...,  3,  3, 18],
       [ 0,  0,  0, ...,  6,  3,  1],
       [ 0,  0,  0, ...,  1,  2,  2]])

# Frequency based feature engineering

#### Applying Tfidf vectorizer

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range=(1,4), lowercase=False, max_features=1000)
vectorizer.fit(X_train['Incident_Drug'].values) # fit has to happen only on train data

vectorizer.get_feature_names_out()[:10]


array(['DRUG_TYPE_0', 'DRUG_TYPE_0 DRUG_TYPE_0',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_0',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_0',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_1',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_2',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_6',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_0 PRIMARY_DIAGNOSIS',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_1',
       'DRUG_TYPE_0 DRUG_TYPE_0 DRUG_TYPE_1 DRUG_TYPE_0'], dtype=object)

In [46]:
X_train_tfidf = vectorizer.transform(X_train['Incident_Drug'].values)
X_test_tfidf = vectorizer.transform(X_test['Incident_Drug'].values)

In [47]:
print(X_train_tfidf.shape, X_test_tfidf.shape)

(21625, 1000) (5407, 1000)


# Saving Vectorizer and tokenizer in pickle file

In [135]:
import pickle as pk

In [136]:
with open('tokens1.pkl','wb') as f:
    pk.dump(tokenizer,f)

In [137]:
with open('vectors1.pkl','wb') as f:
    pk.dump(vectorizer,f)

### Inputs

In [48]:
import ast

In [49]:
X_train['Time_based_features']

26885    [23, 217, 4, 11, 0, 0, 21, 0, 2, 24, 42, 8, 76...
3139     [60, 0, 0, 25, 0, 1, 1, 6, 0, 0, 0, 0, 0, 0, 2...
25384    [89, 63, 35, 27, 27, 24, 148, 13, 0, 56, 75, 7...
7260     [41, 16, 0, 1, 44, 38, 0, 5, 10, 34, 48, 0, 5,...
6220     [232, 93, 0, 0, 0, 0, 0, 36, 24, 39, 23, 18, 1...
                               ...                        
615      [19, 0, 11, 33, 19, 10, 32, 30, 33, 29, 13, 22...
20218    [0, 14, 10, 4, 0, 14, 3, 0, 12, 13, 3, 11, 10,...
11724    [0, 20, 16, 9, 16, 0, 30, 0, 30, 30, 7, 29, 0,...
1096     [58, 37, 145, 33, 27, 0, 0, 0, 0, 0, 3, 47, 0,...
21517    [21, 8, 19, 16, 0, 7, 5, 22, 5, 11, 13, 10, 2,...
Name: Time_based_features, Length: 21625, dtype: object

# X_train desired format

In [52]:
import numpy as np

In [53]:
X_train['Time_based_features'] = X_train['Time_based_features'].apply(lambda x: np.array(x))

# Convert the 'Time_based_features' column to NumPy arrays
Time_based_X_train = np.array(X_train['Time_based_features'].values.tolist())

# Print the new array
print(Time_based_X_train)
print(Time_based_X_train.shape)

[[ 23 217   4 ...   0   0   0]
 [ 60   0   0 ...   0   0   0]
 [ 89  63  35 ...   0   0   0]
 ...
 [  0  20  16 ...   0   0   0]
 [ 58  37 145 ...   0   0   0]
 [ 21   8  19 ...   0   0   0]]
(21625, 1645)


# X_test desired format

In [54]:
X_test['Time_based_features'] = X_test['Time_based_features'].apply(lambda x: np.array(x))

# Convert the 'Time_based_features' column to NumPy arrays
Time_based_X_test = np.array(X_test['Time_based_features'].values.tolist())

# Print the new array
print(Time_based_X_test)
print(Time_based_X_test.shape)

[[10 21 34 ...  0  0  0]
 [ 8 20 21 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [11 26  5 ...  0  0  0]
 [13  6  0 ...  0  0  0]]
(5407, 1645)


In [55]:
train_X=[pad_train,Time_based_X_train,X_train_tfidf.toarray()]
test_X=[pad_test,Time_based_X_test, X_test_tfidf.toarray()]

train_y=y_train.values
test_y=y_test.values

In [56]:
train_X

[array([[ 0,  0,  0, ...,  1,  4,  5],
        [ 0,  0,  0, ...,  2,  1,  4],
        [ 0,  0,  0, ...,  1,  3,  8],
        ...,
        [ 0,  0,  0, ...,  2,  4, 18],
        [ 0,  0,  0, ..., 39,  2,  1],
        [ 0,  0,  0, ...,  6,  5,  5]]),
 array([[ 23, 217,   4, ...,   0,   0,   0],
        [ 60,   0,   0, ...,   0,   0,   0],
        [ 89,  63,  35, ...,   0,   0,   0],
        ...,
        [  0,  20,  16, ...,   0,   0,   0],
        [ 58,  37, 145, ...,   0,   0,   0],
        [ 21,   8,  19, ...,   0,   0,   0]]),
 array([[0.13206854, 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.29871422, 0.10880255, 0.0266055 , ..., 0.        , 0.        ,
         0.        ],
        [0.09207234, 0.02515206, 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.15196786, 0.02576741, 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.2453808 , 0.04468829, 0.        , ..., 0.        , 0.     

In [57]:
train_y

array([1, 0, 1, ..., 0, 0, 1], dtype=int64)

In [58]:
test_y

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [59]:
test_X

[array([[ 0,  0,  0, ...,  5,  5,  2],
        [ 0,  0,  0, ...,  1, 10, 10],
        [ 0,  0,  0, ...,  8,  6, 10],
        ...,
        [ 0,  0,  0, ...,  3,  3, 18],
        [ 0,  0,  0, ...,  6,  3,  1],
        [ 0,  0,  0, ...,  1,  2,  2]]),
 array([[10, 21, 34, ...,  0,  0,  0],
        [ 8, 20, 21, ...,  0,  0,  0],
        [ 0,  2,  0, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [11, 26,  5, ...,  0,  0,  0],
        [13,  6,  0, ...,  0,  0,  0]]),
 array([[0.0706942 , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.0402242 , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.167717  , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.1239256 , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [

In [60]:
len(tokenizer.word_index)+1

57

### ------- Model building--------

In [61]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, LSTM, Flatten, Dense, Dropout, concatenate
from tensorflow.keras.regularizers import l2
from tensorflow.keras.initializers import HeNormal
from keras.models import Model

# Input layers
input_layer_1 = Input(shape=pad_train.shape[1], name="Input_layer_for_LSTM_based_features")
input_layer_2 = Input(shape=(len(X_train['Time_based_features'][0]),), name='Input_layer_for_Time_based_features')
input_layer_3 = Input(shape=X_train_tfidf.shape[1], name="Input_layer_for_frequency_based_features")

# Embedding layers
embedding_layer_1 = Embedding(input_dim=57, output_dim=128, input_length=pad_train.shape[1], name="Embedding_layer_1")(input_layer_1)

# LSTM layers
lstm_layer_1 = LSTM(64, return_sequences=True, name="LSTM_layer_1")(embedding_layer_1)

# Flatten layers
flatten_layer_1 = Flatten(name="Flatten_layer_1")(lstm_layer_1)

# Dense layers
dense_0 = Dense(256, activation='relu', name='Dense_for_tfidf_input')(input_layer_3)
concatenated_tensor = concatenate([flatten_layer_1, dense_0], axis=1)
dense_1 = Dense(256, activation='relu', kernel_initializer=HeNormal(), kernel_regularizer=l2(0.0001), name='Dense_layer_after_concat')(concatenated_tensor)
drop_1 = Dropout(0.5, name="Dropout_1")(dense_1)
dense_2 = Dense(128, activation='relu', kernel_initializer=HeNormal(), kernel_regularizer=l2(0.0001), name='Dense_2')(drop_1)
drop_2 = Dropout(0.5, name="Dropout_2")(dense_2)
dense_3 = Dense(64, activation='relu', kernel_initializer=HeNormal(), kernel_regularizer=l2(0.0001), name='Dense_3')(drop_2)

# Output layer
output_layer = Dense(1, activation='sigmoid', name='Output_layer_for_binary_classification')(dense_3)

# Put all the input layers in a list format
input_layers = [input_layer_1, input_layer_2, input_layer_3]

# Define the model
model = Model(inputs=input_layers, outputs=output_layer)

# Print the model summary
model.summary()


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 Input_layer_for_LSTM_based  [(None, 1645)]               0         []                            
 _features (InputLayer)                                                                           
                                                                                                  
 Embedding_layer_1 (Embeddi  (None, 1645, 128)            7296      ['Input_layer_for_LSTM_based_f
 ng)                                                                eatures[0][0]']               
                                                                                                  
 LSTM_layer_1 (LSTM)         (None, 1645, 64)             49408     ['Embedding_layer_1[0][0]']   
                                                                                              

In [62]:
opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
# Specify the batch size in model.fit
batch_size = 16
model.fit(train_X, train_y, epochs=10, validation_data = (test_X,test_y),batch_size=16)

Epoch 1/10
1352/1352 [==============================] - 3036s 2s/step - loss: 0.5715 - accuracy: 0.7421 - val_loss: 0.4589 - val_accuracy: 0.8125
Epoch 2/10
1352/1352 [==============================] - 2976s 2s/step - loss: 0.4457 - accuracy: 0.8218 - val_loss: 0.4078 - val_accuracy: 0.8417
Epoch 3/10
1352/1352 [==============================] - 2676s 2s/step - loss: 0.4021 - accuracy: 0.8411 - val_loss: 0.3842 - val_accuracy: 0.8502
Epoch 4/10
1352/1352 [==============================] - 1739s 1s/step - loss: 0.3775 - accuracy: 0.8512 - val_loss: 0.3716 - val_accuracy: 0.8559
Epoch 5/10
1352/1352 [==============================] - 1697s 1s/step - loss: 0.3581 - accuracy: 0.8608 - val_loss: 0.3630 - val_accuracy: 0.8561
Epoch 6/10
1352/1352 [==============================] - 1813s 1s/step - loss: 0.3453 - accuracy: 0.8683 - val_loss: 0.3567 - val_accuracy: 0.8613
Epoch 7/10
1352/1352 [==============================] - 1632s 1s/step - loss: 0.3315 - accuracy: 0.8754 - val_loss: 0.3562 -

# F1-Score

In [63]:
from sklearn.metrics import f1_score

predictions = model.predict(test_X)


threshold = 0.5
binary_predictions = (predictions > threshold).astype(int)


f1 = f1_score(test_y, binary_predictions)

print("F1 Score:", f1)


169/169 [==============================] - 41s 238ms/step
F1 Score: 0.8019297775395337


# Saving the model

In [64]:
model.save("drug.h5")

# ----------------Pipeline for test data------------------

### Loading test data

In [82]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import ast
import pickle as pk
import tensorflow as tf

In [67]:
test_data = pd.read_parquet(r"C:\Users\91882\Downloads\test.parquet")
test_data.head()

Patient-Uid       Date        Incident
0  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08  SYMPTOM_TYPE_0
1  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17     DRUG_TYPE_0
2  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01     DRUG_TYPE_2
3  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05     DRUG_TYPE_1
4  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-11-04  SYMPTOM_TYPE_0

### Asusual processing the dataset like we done during model development stage

In [68]:
test_data['Date'] = pd.to_datetime(test_data['Date'])

# Sorting
test_data.sort_values(by=['Patient-Uid', 'Date'], inplace=True)

# Grouping 
test_group_data = test_data.groupby('Patient-Uid')['Incident'].apply(lambda x: ' '.join(x)).reset_index()


test_group_data.head()

Patient-Uid  \
0  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f   
1  a0f9e9f9-1c7c-11ec-b565-16262ee38c7f   
2  a0f9ea43-1c7c-11ec-aa10-16262ee38c7f   
3  a0f9ea7c-1c7c-11ec-af15-16262ee38c7f   
4  a0f9eab1-1c7c-11ec-a732-16262ee38c7f   

                                            Incident  
0  DRUG_TYPE_7 SYMPTOM_TYPE_0 TEST_TYPE_0 DRUG_TY...  
1  PRIMARY_DIAGNOSIS DRUG_TYPE_2 DRUG_TYPE_6 DRUG...  
2  DRUG_TYPE_1 DRUG_TYPE_6 DRUG_TYPE_1 DRUG_TYPE_...  
3  DRUG_TYPE_6 PRIMARY_DIAGNOSIS DRUG_TYPE_3 DRUG...  
4  DRUG_TYPE_2 DRUG_TYPE_2 PRIMARY_DIAGNOSIS DRUG...

In [69]:
patients= test_data.groupby('Patient-Uid')

print(patients.ngroups)

max_length=1645

count=0

Time_based_features=[]

incident_drug = test_group_data['Incident'].values


for group_name, group_data in patients:

    #the gap history of each patient
    temp_list=[]

    for j in range(len(incident_drug[count].split())-1):
            # difference between the consecutive dates in days
            temp_list.append((group_data["Date"].iloc[j+1]-group_data["Date"].iloc[j]).days)
    #pad the gap vector with the max_length 
    temp_list.extend(list(np.zeros(shape=max_length-len(temp_list),dtype=int)))

    Time_based_features.append(temp_list)
    count+=1

11482


In [70]:
#check the shape
print(len(Time_based_features),len(Time_based_features[0]))

11482 1645


In [71]:
# Convert it to the desired format

In [72]:
Time_based_X_test = np.array([np.array(sublist) for sublist in Time_based_features])

# Print the new array
print(Time_based_X_test)
print(Time_based_X_test.shape)

[[168   0   0 ...   0   0   0]
 [  1  17   0 ...   0   0   0]
 [ 19  11  17 ...   0   0   0]
 ...
 [ 38  39  16 ...   0   0   0]
 [158  36  39 ...   0   0   0]
 [  0  17   7 ...   0   0   0]]
(11482, 1645)


### Loading tokens and vectorized pickle file

In [77]:
# Load the vectorizer from the file
with open('tokens1.pkl','rb') as f:
    loaded_tokenizer = pk.load(f)

# Encoding the text and applying front-side padding for the validation data
X_test_encoded = loaded_tokenizer.texts_to_sequences(test_group_data['Incident'].values)
X_test_padded = tf.keras.preprocessing.sequence.pad_sequences(X_test_encoded, padding='pre', maxlen=1645)

X_test_padded.shape

(11482, 1645)

In [79]:
with open('vectors1.pkl','rb') as f:
    loaded_tfidf_vectorizer = pk.load(f)

X_test_tfidf = loaded_tfidf_vectorizer.transform(test_group_data['Incident'].values)

print(X_test_tfidf.shape)

(11482, 1000)


In [80]:
test_X=[X_test_padded,Time_based_X_test, X_test_tfidf.toarray()]

# loading the model

In [83]:
loaded_model = tf.keras.models.load_model('drug.h5')

In [ ]:
y_pred_test= loaded_model.predict(test_X)
y_label_pred_test= [1 if d>=0.5 else 0 for d in y_pred_test]

223/359 [=================>............] - ETA: 32s

# Submission format

In [ ]:
submit=pd.DataFrame()

submit['Patient-Uid']=grouped['Patient-Uid'].values
final_submission['label']=y_label_pred_test

final_submission.head()